version: '3'

services:
  spark:
    image: bitnami/spark:latest
    ports:
      - "8080:8080" # Spark master web UI
    environment:
      - SPARK_MODE=master

  minio:
    image: minio/minio
    ports:
      - "9000:9000" # MinIO API and web UI
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  minio_data:
