version: '3'

services:
  spark:
    image: bitnami/spark:latest
    ports:
      - "8080:8080" # Spark master web UI
    environment:
      - SPARK_MODE=master

  minio:
    image: minio/minio
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Web UI
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root-pass
    command: server /data --console-address :9001
    volumes:
      - minio_data:/data

volumes:
  minio_data:
